---
server:
  port: 1020
spring:
  profiles: local
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
  mvc:
    dispatch-options-request: true
  application:
    name: interaction
  datasource:
    url: "jdbc:mysql://localhost:3306/test_data?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false"
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    validationQuery: SELECT 1 FROM DUAL
    hikari:
      max-lifetime: 1200000
      connection-timeout: 60000
      validation-timeout: 3000
      idle-timeout: 30000
      minimum-idle: 10
      maximum-pool-size: 10
      connection-test-query: select 1
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 30
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        url-pattern: "/druid/*"
        login-username: "druid"
        login-password: "druid123123"
      WebStatFilter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      validation-query: "select 1"
  jpa:
    hibernate:
      dialect:
        storage_engine: innodb
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 150
  redis:
    host: localhost
    port: 6379
    timeout: 5000
    password: "!QAZXDR%"


app:
  live:
    api: http://localhost:1030
  wx:
    miniprogram:
      scanurl: "http://scan.vidyo.net.cn/miniprogram"
